# Generated by Django 5.0 on 2024-01-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogdetails",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="dogdetails",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
